name = "v2ray"
main = "_worker.js"
compatibility_date = "2025-11-22"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "198.217.251.250:443"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
