name = "chiddy-cloud-workers"
main = "_worker.js"
compatibility_date = "2025-11-04"

keep_vars = true

[vars]
ADMIN = "chiddy2025"
UUID = "c04cb9f4-0a5a-4f13-9569-a385f96f228d"

# KV Namespace binding
[[kv_namespaces]]
binding = "CHIDDY_KV"
id = "3a6e01c4b0614a818602a968644537a5"
